MasterPoBundle\Entity\Product:
    type: entity
    table: null
    repositoryClass: MasterPoBundle\Repository\ProductRepository
    oneToMany:
        product_photo_galleries:
            targetEntity: MasterPoBundle\Entity\ProductPhotoGalleries
            mappedBy: product
    manyToOne:
        profile:
            targetEntity: MasterPoBundle\Entity\Profile
            inversedBy: products
            joinColumn:
                name: profile_id
                referencedColumnName: id

        sub_category:
            targetEntity: MasterPoBundle\Entity\SubCategory
            inversedBy: products
            joinColumn:
                name: sub_categry_id
                referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        page_viewed:
            type: integer
            length: 255
            options:
                default: 0
        phone_viewed:
            type: integer
            length: 255
            options:
                default: 0
        active:
            type: boolean
            options:
                default: true
        top:
            type: boolean
            options:
                default: false
        description:
            type: text
            length: 4096
        price:
            type: decimal
            precision: 10
            scale: 2

        exchange:
            type: boolean
            options:
                default: false
        vip:
            type: boolean
            options:
                default: false
        name:
            type: string
            length: 64
        slug:
            type: string
            length: 128
            gedmo:
                slug:
                    separator: _
                    style: camel
                    fields:
                      - name
    lifecycleCallbacks: {  }
