MasterPoBundle\Entity\Region:
    type: entity
    table: null
    repositoryClass: MasterPoBundle\Repository\RegionRepository
    oneToMany:
        cities:
            targetEntity: MasterPoBundle\Entity\City
            mappedBy: region
    manyToOne:
        country:
            targetEntity: MasterPoBundle\Entity\Country
            inversedBy: regions
            joinColumn:
                name: country_id
                referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        slug:
            type: string
            length: 128
            gedmo:
                slug:
                    separator: _
                    style: camel
                    fields:
                      - name
        name:
            type: string
            length: 255
    indexes:
        search_idx:
            columns: slug
    lifecycleCallbacks: {  }
