MasterPoBundle\Entity\User:
    type:  entity
    table: fos_user
    repositoryClass: MasterPoBundle\Repository\UserRepository
    oneToOne:
        profile:
            targetEntity: MasterPoBundle\Entity\Profile
            mappedBy: user
    oneToMany:
        refresh_tokens:
            targetEntity: MasterPoBundle\Entity\RefreshToken
            mappedBy: user
        access_tokens:
            targetEntity: MasterPoBundle\Entity\AccessToken
            mappedBy: user
        auth_codes:
            targetEntity: MasterPoBundle\Entity\AuthCode
            mappedBy: user

    id:
        id:
            type: integer
            generator:
                strategy: AUTO