# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true

    app.event_listeners.locale_rewrite_listener:
        class: MasterPoBundle\EventListener\LocaleRewriteListener
        arguments: ["@router", "%kernel.default_locale%", "%locale_supported%"]
        tags:
          - { name: kernel.event_subscriber }
#    app.user_locale_listener:
#        class: MasterPoBundle\EventListener\UserLocaleListener
#        arguments: ['@session']
#        tags:
#            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }
    app.img_uploader:
        class: MasterPoBundle\Service\FileUploader
        arguments: ['%catalog.path%']

#    master.new_message:
#        class: SadisamBundle\Service\NewMessage
#        arguments: [ "@twig", "@mailer" ]
    rs_user.registration_complet:
        class: MasterPoBundle\EventListener\RegistrationConfirmListener
        arguments: ['@router']
        tags:
            - { name: kernel.event_subscriber }

    top.register:
        class: MasterPoBundle\EventListener\RegisterListener
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_subscriber }


#
#    app.form.registration:
#        class: MasterPoBundle\Form\RegistrationType
#        tags:
#            - { name: form.type, alias: app_user_registration }
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
#    my.oauth_aware.user_provider.service:
#        class: HWI\Bundle\OAuthBundle\Security\Core\User\FOSUBUserProvider
#        arguments:
#            - '@fos_user.user_manager.default'
#            - ['pass properties as array']
