<?php

namespace MasterPoBundle\Repository;

/**
 * ProductPhotoGalleriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductPhotoGalleriesRepository extends \Doctrine\ORM\EntityRepository
{
}
