<?php

namespace MasterPoBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function getVipProducts()
    {
        return $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.active = 1')
//            TODO change after test
//            ->andWhere('p.vip = 1')
            ->orderBy('p.id', 'DESC');
    }

}
